---
title       : Introducting "How many Cylinders is your ride?"
subtitle    : Data Science Specialization -Developing Data Product
author      : Fan Chun Pong
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Agenda

1. What can this application do?
2. Why do it?
3. What is next?

--- .class #id 

## What can this application do?
Basically, the by providing the application with your car's MPG, the application
will predict the number of cylinder of your car's engine.

Many may think this is a pretty useless application. But with many countries trying
to reduce emission level, this application can be expanded to help educate car
owners or prospective car owners on emission level of their cars.

More information in the "What next?" slide.

---

## Why do it?
This application is just a proof of concept for a simply, easy to create,
interactive platform to educate educate car owners or prospective car owners on 
emission level of their cars and the impact on our envirnoment.

---

## What is next?
As a rapid prototype, this application uses the data from the mtcars dataset,
however, moving forward below are some feature to be implemented to make this 
application more useful:

1. Engine Capactiy/No. of Cylinders/Horsepower to Emission ratio prediction
With these information, a car owner/prospective owner would be able to known 
approximately how much emission will be generated by his/her car.

2. A world pollution trend visualization tool to help show the world how bad is 
the emission level around the world.






